# Generated by Django 4.2.1 on 2025-06-07 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_remove_user_profile_picture_user_profile_picture_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kakao_profile_picture_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture_key',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
