# Generated by Django 4.2.1 on 2025-06-07 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_user_kakao_profile_picture_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='kakao_profile_picture_url',
        ),
    ]
