services:
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - ./data/db:/var/lib/mysql
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5

  redis:
    image: redis:7.2
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    command: server /data --console-address ":9001"
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./data/minio:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 10
  web:
      build: ./backend
      command: python manage.py runserver 0.0.0.0:8000
      ports:
        - "8000:8000"
      env_file:
        - .env
      volumes:
        #- ./mysql:/etc/mysql/conf.d
        - ./backend:/backend
      depends_on:
        db:
          condition: service_healthy  # DB가 정상적으로 실행될 때까지 기다림
        redis:
          condition: service_healthy
  chat-server:
    build:
      context: ./chat-server
    command: node server.js
    ports:
      - "3000:3000"
    # volumes:
    #   - ./chat-server:/usr/src/app
    env_file:
      - .env
    depends_on:
        db:
          condition: service_healthy  # DB가 정상적으로 실행될 때까지 기다림
        redis:
          condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 10s
      retries: 3