services:
  db:
    image: mysql:8.0
    ports:
    - "3306:3306"
    volumes:
      - ./data/db:/var/lib/mysql
    env_file:
      - .env
  web:
    build: ./backend
    command: ["/usr/local/bin/wait-for-it.sh", "db:3306", "--", "python", "manage.py", "runserver", "0.0.0.0:8000"]
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./mysql:/etc/mysql/conf.d
    depends_on:
      db:
        condition: service_started
  minio:
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    command: server /data --console-address ":9001"
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./data/minio:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 10