services:
  db:
    image: mysql:8.0
    volumes:
      - ./data/db:/var/lib/mysql
    env_file:
      - .env
  web:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./mysql:/etc/mysql/conf.d
    depends_on:
      - db
