# Generated by Django 4.2.1 on 2025-05-11 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_message_read_by_message_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(default='text', max_length=10),
        ),
    ]
