# Generated by Django 4.2.1 on 2025-05-31 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='헌혈의 집')),
                ('address', models.CharField(max_length=255, verbose_name='주소지')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='전화번호')),
                ('center_type', models.CharField(blank=True, max_length=50, verbose_name='구분')),
                ('blood_office', models.CharField(blank=True, max_length=50, verbose_name='혈액원')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
