# Generated by Django 4.2.1 on 2025-05-18 10:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(16), django.core.validators.MaxValueValidator(70)])),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('blood_type', models.CharField(choices=[('A+', 'A Positive'), ('A-', 'A Negative'), ('B+', 'B Positive'), ('B-', 'B Negative'), ('AB+', 'AB Positive'), ('AB-', 'AB Negative'), ('O+', 'O Positive'), ('O-', 'O Negative')], max_length=3)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='donation_images/')),
                ('location', models.CharField(max_length=255)),
                ('donation_due_date', models.DateField()),
                ('donator_registered_id', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(code='invalid_donator_id', message='ID must be in the format XXXXXX-XXXX (6 digits, hyphen, 4 digits).', regex='^\\d{6}-\\d{4}$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_requests', to='login.user')),
            ],
        ),
        migrations.CreateModel(
            name='SelectedMatchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_at', models.DateTimeField(auto_now_add=True)),
                ('donation_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_matches', to='donations.donationrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_matches', to='login.user')),
            ],
            options={
                'unique_together': {('user', 'donation_request')},
            },
        ),
        migrations.CreateModel(
            name='RejectedMatchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rejected_matches', to='donations.donationrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rejected_matches', to='login.user')),
            ],
            options={
                'unique_together': {('user', 'donation_request')},
            },
        ),
    ]
