# Generated by Django 4.2.1 on 2025-05-15 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_alter_donationrequest_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationrequest',
            name='image',
            field=models.ImageField(blank=True, storage='minio_storage', upload_to='donation_images/'),
        ),
    ]
